debug: true

torres:
  torre1:
    # Item ativável da torre
    item:
      material: "CACTUS:0"
      name: "&eTorre de Cacto Pequena"
      lore:
        - "&7Use essa torre de cacto"
        - "&7em seu terreno."
        - ""
        - " &fCamadas: &73"
        - ""
        - "&aClique no chão para colocar"
    # Quantia de camadas
    layers: 3

  torre2:
    # Item ativável da torre
    item:
      material: "CACTUS:0"
      name: "&eTorre de Cacto Média"
      lore:
        - "&7Use essa torre de cacto"
        - "&7em seu terreno."
        - ""
        - " &fCamadas: &75"
        - ""
        - "&aClique no chão para colocar"
    # Quantia de camadas
    layers: 5

  torre3:
    # Item ativável da torre
    item:
      material: "CACTUS:0"
      name: "&eTorre de Cacto Grande"
      lore:
        - "&7Use essa torre de cacto"
        - "&7em seu terreno."
        - ""
        - " &fCamadas: &77"
        - ""
        - "&aClique no chão para colocar"
    # Quantia de camadas
    layers: 7

messages:
  no-permission: "&cVocê não tem permissão para isso!"
  send-tower: "&aVocê deu {AMOUNT} {TORRE-NAME} &apara {JOGADOR}!"
  receive-tower: "&aVocê recebeu {AMOUNT} {TORRE-NAME}&a!"
  cant-put: "&cVocê não pode colocar a torre aqui!"
  tower-placed: "&aTorre colocada com sucesso!"